// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivdeqxwuosarrminthoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZGVxeHd1b3NhcnJtaW50aG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzA4NzcsImV4cCI6MjA2OTkwNjg3N30.XjOqunhWnzw7vSYpFzJfVA8W7EhJj9kQU5gaH0p5JKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});